In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import scipy

In [71]:
def getColstatistic(df, tag):
    # Calculate mean and standard deviation for each row
    means = df.mean(axis=1)
    std_devs = df.std(axis=1)

    # Add mean and standard deviation columns to the DataFrame
    df[f'{tag}_mean'] = means/10000
    df[f'{tag}_std'] = std_devs/10000
    return df.iloc[:,-2:]


def getColstatisticBySearch(df, search_tag, out_tag):
    # print(df.shape)
    column_names = list(df.columns)
    col_find = []
    for col in column_names:
        if re.search(search_tag, col):
            # print(f'{col} find search_tag {search_tag}')
            col_find.append(col)
    
    df_out = df[col_find]
    print(f"df out shape is {df_out.shape}")
    means = df_out.mean(axis=1)
    std_devs = df_out.std(axis=1)
    skew_v = df_out.skew(axis=1)
    kurt_v = df_out.kurt(axis=1)
    df_out[f'{out_tag}_mean'] = means/10000
    df_out[f'{out_tag}_std'] = std_devs/10000
    df_out[f'{out_tag}_skew'] = skew_v/10000
    df_out[f'{out_tag}_kurt'] = kurt_v/10000
    print(df_out.shape)
    
    return df_out.iloc[:,-4:]

In [ ]:
df = pd.read_csv("../Vegetation_Indices/NDVI_EVI.csv")
df_evi2005 = df.loc[:,'evi_2005-01':'evi_2005-12']
df_evi2005 = getColstatistic(df=df_evi2005, tag='evi2005')

df_evi2006 = df.loc[:,'evi_2006-01':'evi_2006-12']
df_evi2006 = getColstatistic(df=df_evi2006, tag='evi2006')

df_evi2007 = df.loc[:,'evi_2007-01':'evi_2007-12']
df_evi2007 = getColstatistic(df=df_evi2007, tag='evi2007')

df_evi2008 = df.loc[:,'evi_2008-01':'evi_2008-12']
df_evi2008 = getColstatistic(df=df_evi2008, tag='evi2008')

df_evi_jan = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-01", out_tag="evi_jan")
df_evi_feb = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-02", out_tag="evi_feb")
df_evi_mar = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-03", out_tag="evi_mar")
df_evi_apr = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-04", out_tag="evi_apr")
df_evi_may = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-05", out_tag="evi_may")
df_evi_jun = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-06", out_tag="evi_jun")
df_evi_jul = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-07", out_tag="evi_jul")
df_evi_aug = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-08", out_tag="evi_aug")
df_evi_sep = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-09", out_tag="evi_sep")
df_evi_oct = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-10", out_tag="evi_oct")
df_evi_nov = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-11", out_tag="evi_nov")
df_evi_dec = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-12", out_tag="evi_dec")

evi_list = [df_evi2005, df_evi2006, df_evi2007, df_evi2008, 
            df_evi_jan, df_evi_feb, df_evi_mar, df_evi_apr, df_evi_may, df_evi_jun, 
            df_evi_aug, df_evi_sep, df_evi_oct, df_evi_nov, df_evi_dec]
evi_stat = pd.concat(evi_list, axis=1)
evi_stat

In [ ]:
df_evi2005 = df.loc[:,'evi_2005-01':'evi_2005-12']
df_evi2005 = getColstatistic(df=df_evi2005, tag='evi2005')

df_evi2006 = df.loc[:,'evi_2006-01':'evi_2006-12']
df_evi2006 = getColstatistic(df=df_evi2006, tag='evi2006')

df_evi2007 = df.loc[:,'evi_2007-01':'evi_2007-12']
df_evi2007 = getColstatistic(df=df_evi2007, tag='evi2007')

df_evi2008 = df.loc[:,'evi_2008-01':'evi_2008-12']
df_evi2008 = getColstatistic(df=df_evi2008, tag='evi2008')

df_evi_jan = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-01", out_tag="evi_jan")
df_evi_feb = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-02", out_tag="evi_feb")
df_evi_mar = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-03", out_tag="evi_mar")
df_evi_apr = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-04", out_tag="evi_apr")
df_evi_may = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-05", out_tag="evi_may")
df_evi_jun = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-06", out_tag="evi_jun")
df_evi_jul = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-07", out_tag="evi_jul")
df_evi_aug = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-08", out_tag="evi_aug")
df_evi_sep = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-09", out_tag="evi_sep")
df_evi_oct = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-10", out_tag="evi_oct")
df_evi_nov = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-11", out_tag="evi_nov")
df_evi_dec = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-12", out_tag="evi_dec")

evi_list = [df_evi2005, df_evi2006, df_evi2007, df_evi2008, 
            df_evi_jan, df_evi_feb, df_evi_mar, df_evi_apr, df_evi_may, df_evi_jun, 
            df_evi_aug, df_evi_sep, df_evi_oct, df_evi_nov, df_evi_dec]
evi_stat = pd.concat(evi_list, axis=1)
evi_stat

In [49]:
df_ndvi2005 = df.loc[:,'ndvi_2005-01':'ndvi_2005-12']
df_ndvi2005 = getColstatistic(df=df_ndvi2005, tag='ndvi2005')

df_ndvi2006 = df.loc[:,'ndvi_2006-01':'ndvi_2006-12']
df_ndvi2006 = getColstatistic(df=df_ndvi2006, tag='ndvi2006')

df_ndvi2007 = df.loc[:,'ndvi_2007-01':'ndvi_2007-12']
df_ndvi2007 = getColstatistic(df=df_ndvi2007, tag='ndvi2007')

df_ndvi2008 = df.loc[:,'ndvi_2008-01':'ndvi_2008-12']
df_ndvi2008 = getColstatistic(df=df_ndvi2008, tag='ndvi2008')

df_ndvi_jan = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-01", out_tag="ndvi_jan")
df_ndvi_feb = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-02", out_tag="ndvi_feb")
df_ndvi_mar = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-03", out_tag="ndvi_mar")
df_ndvi_apr = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-04", out_tag="ndvi_apr")
df_ndvi_may = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-05", out_tag="ndvi_may")
df_ndvi_jun = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-06", out_tag="ndvi_jun")
df_ndvi_jul = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-07", out_tag="ndvi_jul")
df_ndvi_aug = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-08", out_tag="ndvi_aug")
df_ndvi_sep = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-09", out_tag="ndvi_sep")
df_ndvi_oct = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-10", out_tag="ndvi_oct")
df_ndvi_nov = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-11", out_tag="ndvi_nov")
df_ndvi_dec = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-12", out_tag="ndvi_dec")

ndvi_list = [df_ndvi2005, df_ndvi2006, df_ndvi2007, df_ndvi2008, 
            df_ndvi_jan, df_ndvi_feb, df_ndvi_mar, df_ndvi_apr, df_ndvi_may, df_ndvi_jun, 
            df_ndvi_aug, df_ndvi_sep, df_ndvi_oct, df_ndvi_nov, df_ndvi_dec]
ndvi_stat = pd.concat(ndvi_list, axis=1)

,ndvi2005_mean,ndvi2005_std,ndvi2006_mean,ndvi2006_std,ndvi2007_mean,ndvi2007_std,ndvi2008_mean,ndvi2008_std,ndvi_jan_mean,ndvi_jan_std,...,ndvi_aug_mean,ndvi_aug_std,ndvi_sep_mean,ndvi_sep_std,ndvi_oct_mean,ndvi_oct_std,ndvi_nov_mean,ndvi_nov_std,ndvi_dec_mean,ndvi_dec_std
0,0.637433,0.110948,0.615675,0.095581,0.556917,0.120725,0.637267,0.128308,0.506225,0.055385,...,0.728750,0.052780,0.739900,0.070917,0.714925,0.035103,0.650375,0.055600,0.569325,0.026234
1,0.641042,0.084695,0.605033,0.092970,0.630517,0.096732,0.636233,0.052777,0.544100,0.034581,...,0.688025,0.066841,0.709725,0.040902,0.701600,0.036860,0.625875,0.039656,0.590425,0.029281
2,0.657942,0.134317,0.618050,0.158449,0.669200,0.136557,0.682967,0.116354,0.566875,0.085225,...,0.784175,0.030140,0.763350,0.034337,0.746500,0.045839,0.665000,0.096119,0.618100,0.113841
3,0.579025,0.152534,0.598892,0.169426,0.625800,0.149961,0.608292,0.119709,0.387475,0.028035,...,0.713250,0.021041,0.762400,0.005728,0.706600,0.038161,0.606800,0.118046,0.576100,0.117365
4,0.639317,0.127267,0.607767,0.147037,0.640808,0.047156,0.653692,0.061168,0.559150,0.068992,...,0.720425,0.044878,0.716175,0.051303,0.717125,0.053979,0.650625,0.086135,0.624125,0.070814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,0.606758,0.071198,0.570050,0.068006,0.573692,0.058341,0.555075,0.049594,0.536050,0.025579,...,0.626800,0.059880,0.664600,0.031629,0.641550,0.021434,0.616675,0.031106,0.574775,0.033779
1076,0.684158,0.058609,0.673825,0.033373,0.691833,0.038913,0.700467,0.037893,0.673100,0.027103,...,0.694850,0.023946,0.723850,0.010296,0.726350,0.023544,0.698025,0.035437,0.681725,0.022111
1077,0.780958,0.048931,0.738800,0.046509,0.748508,0.038177,0.736400,0.036270,0.724825,0.011088,...,0.817525,0.027822,0.806550,0.024312,0.766575,0.049814,0.739350,0.014624,0.735350,0.027495
1078,0.467892,0.076813,0.453175,0.056307,0.465583,0.052712,0.419617,0.038662,0.413400,0.043454,...,0.506625,0.042128,0.529725,0.045592,0.473725,0.046843,0.445125,0.021207,0.467100,0.025503
1079,0.582142,0.099066,0.574883,0.072775,0.539025,0.123858,0.555033,0.053536,0.581350,0.020206,...,0.615900,0.035762,0.670925,0.036177,0.674575,0.040567,0.625500,0.037196,0.608975,0.044579

In [58]:
merge_list = [df_evi2005, df_evi2006, df_evi2007, df_evi2008, 
            df_evi_jan, df_evi_feb, df_evi_mar, df_evi_apr, df_evi_may, df_evi_jun, 
            df_evi_aug, df_evi_sep, df_evi_oct, df_evi_nov, df_evi_dec, df_ndvi2005, df_ndvi2006, df_ndvi2007, df_ndvi2008, 
            df_ndvi_jan, df_ndvi_feb, df_ndvi_mar, df_ndvi_apr, df_ndvi_may, df_ndvi_jun, 
            df_ndvi_aug, df_ndvi_sep, df_ndvi_oct, df_ndvi_nov, df_ndvi_dec]
VIs_df = pd.concat(merge_list, axis=1)
VIs_df = pd.concat([df.iloc[:,:6],VIs_df], axis=1)
print(VIs_df)
VIs_df.to_csv("../Vegetation_Indices/NDVI_EVI_stat.csv", index=False)

      SiteID  Longitude   Latitude      Easting     Northing       CalVal  \
0        824 -80.673297  26.489618  731009.6175  280555.0742  calibration
1        818 -80.629703  26.664214  734816.5356  300047.1635  calibration
2        815 -80.516236  26.776278  745734.3602  312796.3002   validation
3        817 -80.474436  26.569130  750538.8963  289927.4316   validation
4        819 -80.691423  26.599105  728880.4467  292655.8679  calibration
...      ...        ...        ...          ...          ...          ...
1075     524 -81.445848  26.460529  654219.7001  275493.7896  calibration
1076     470 -81.447620  27.903338  650727.7593  435655.7481  calibration
1077    3012 -85.017295  30.217204  302181.6658  690394.2248  calibration
1078    3058 -81.668107  28.543391  627727.2782  506295.9652  calibration
1079     528 -81.891268  26.866231  609120.8594  319686.9694  calibration

      evi2005_mean  evi2005_std  evi2006_mean  evi2006_std  ...  \
0         0.411158     0.124963      0.383967     0.123101  ...
1         0.365767     0.105194      0.336067     0.110680  ...
2         0.406283     0.175276      0.371908     0.193293  ...
3         0.342808     0.180252      0.338667     0.195540  ...
4         0.365167     0.127833      0.356225     0.174229  ...
...            ...          ...           ...          ...  ...
1075      0.381750     0.051737      0.368450     0.068686  ...
1076      0.424592     0.059335      0.420550     0.057068  ...
1077      0.408700     0.076592      0.364900     0.037747  ...
1078      0.302267     0.074471      0.287967     0.044920  ...
1079      0.267600     0.057708      0.268742     0.028783  ...

      ndvi_aug_mean  ndvi_aug_std  ndvi_sep_mean  ndvi_sep_std  ndvi_oct_mean  \
0          0.728750      0.052780       0.739900      0.070917       0.714925
1          0.688025      0.066841       0.709725      0.040902       0.701600
2          0.784175      0.030140       0.763350      0.034337       0.746500
3          0.713250      0.021041       0.762400      0.005728       0.706600
4          0.720425      0.044878       0.716175      0.051303       0.717125
...             ...           ...            ...           ...            ...
1075       0.626800      0.059880       0.664600      0.031629       0.641550
1076       0.694850      0.023946       0.723850      0.010296       0.726350
1077       0.817525      0.027822       0.806550      0.024312       0.766575
1078       0.506625      0.042128       0.529725      0.045592       0.473725
1079       0.615900      0.035762       0.670925      0.036177       0.674575

      ndvi_oct_std  ndvi_nov_mean  ndvi_nov_std  ndvi_dec_mean  ndvi_dec_std
0         0.035103       0.650375      0.055600       0.569325      0.026234
1         0.036860       0.625875      0.039656       0.590425      0.029281
2         0.045839       0.665000      0.096119       0.618100      0.113841
3         0.038161       0.606800      0.118046       0.576100      0.117365
4         0.053979       0.650625      0.086135       0.624125      0.070814
...            ...            ...           ...            ...           ...
1075      0.021434       0.616675      0.031106       0.574775      0.033779
1076      0.023544       0.698025      0.035437       0.681725      0.022111
1077      0.049814       0.739350      0.014624       0.735350      0.027495
1078      0.046843       0.445125      0.021207       0.467100      0.025503
1079      0.040567       0.625500      0.037196       0.608975      0.044579

[1080 rows x 66 columns]

In [23]:
VI0004 = pd.read_csv("./evi_ndvi_2000_2004.csv")
VI0508 = pd.read_csv("./NDVI_EVI_2005_2008.csv")
VI_merge = pd.merge(VI0004, VI0508, on="SiteID", how='left')
VI_merge = VI_merge.drop(columns=VI_merge.columns[126:133])
# VI_merge.to_csv("NDVI_EVI_2000_2008.csv",index=False)
df = VI_merge
df

,SiteID,Longitude_x,Latitude_x,Easting_x,Northing_x,CalVal_x,SOC(kg/m)_x,SOC(t/ha)_x,evi_2000-02,evi_2000-03,...,ndvi_2008-03,ndvi_2008-04,ndvi_2008-05,ndvi_2008-06,ndvi_2008-07,ndvi_2008-08,ndvi_2008-09,ndvi_2008-10,ndvi_2008-11,ndvi_2008-12
0,824,-80.673297,26.489618,731009.6175,280555.0742,calibration,34.145765,341.457651,1768,2008,...,5820,5989,5711,5056,7854,7853,8132,7627,7163,5846
1,818,-80.629703,26.664214,734816.5356,300047.1635,calibration,29.264055,292.640554,2973,2833,...,6126,5923,5995,6743,7060,6990,6836,6768,6557,5597
2,815,-80.516236,26.776278,745734.3602,312796.3002,validation,28.958538,289.585381,1754,2205,...,5480,6616,6896,7995,7590,7569,7402,7650,7352,7448
3,817,-80.474436,26.569130,750538.8963,289927.4316,validation,27.891395,278.913947,1114,1717,...,4936,5658,6025,7304,7064,7282,7555,7062,6172,5479
4,819,-80.691423,26.599105,728880.4467,292655.8679,calibration,27.524106,275.241062,489,1318,...,6244,6861,6221,6929,6539,6781,7181,7192,7066,6578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,524,-81.445848,26.460529,654219.7001,275493.7896,calibration,0.690212,6.902116,2741,3305,...,5231,5356,4854,5141,5544,5725,6184,6322,6135,5902
1076,470,-81.447620,27.903338,650727.7593,435655.7481,calibration,0.653125,6.531247,2947,3528,...,6309,7144,6945,6914,7722,7182,7325,7225,7224,6795
1077,3012,-85.017295,30.217204,302181.6658,690394.2248,calibration,0.599034,5.990340,3405,3576,...,6912,7260,7263,7722,7658,7883,7747,7670,7280,7060
1078,3058,-81.668107,28.543391,627727.2782,506295.9652,calibration,0.457019,4.570194,2118,2242,...,3798,4058,4082,4679,3675,4665,4668,4289,4476,4383
1079,528,-81.891268,26.866231,609120.8594,319686.9694,calibration,0.451535,4.515352,1352,1875,...,5246,5038,4481,5215,5562,5959,6290,6327,5916,5493

In [72]:
# get mean and std of evi from same month
df_evi_jan = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-01", out_tag="evi_jan")
df_evi_feb = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-02", out_tag="evi_feb")
df_evi_mar = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-03", out_tag="evi_mar")
df_evi_apr = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-04", out_tag="evi_apr")
df_evi_may = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-05", out_tag="evi_may")
df_evi_jun = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-06", out_tag="evi_jun")
df_evi_jul = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-07", out_tag="evi_jul")
df_evi_aug = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-08", out_tag="evi_aug")
df_evi_sep = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-09", out_tag="evi_sep")
df_evi_oct = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-10", out_tag="evi_oct")
df_evi_nov = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-11", out_tag="evi_nov")
df_evi_dec = getColstatisticBySearch(df=df, search_tag=r"evi_\d\d\d\d-12", out_tag="evi_dec")

# # get mean and std of ndvi from same month
df_ndvi_jan = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-01", out_tag="ndvi_jan")
df_ndvi_feb = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-02", out_tag="ndvi_feb")
df_ndvi_mar = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-03", out_tag="ndvi_mar")
df_ndvi_apr = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-04", out_tag="ndvi_apr")
df_ndvi_may = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-05", out_tag="ndvi_may")
df_ndvi_jun = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-06", out_tag="ndvi_jun")
df_ndvi_jul = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-07", out_tag="ndvi_jul")
df_ndvi_aug = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-08", out_tag="ndvi_aug")
df_ndvi_sep = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-09", out_tag="ndvi_sep")
df_ndvi_oct = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-10", out_tag="ndvi_oct")
df_ndvi_nov = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-11", out_tag="ndvi_nov")
df_ndvi_dec = getColstatisticBySearch(df=df, search_tag=r"ndvi_\d\d\d\d-12", out_tag="ndvi_dec")

df out shape is (1080, 8)
(1080, 12)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 8)
(1080, 12)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)
df out shape is (1080, 9)
(1080, 13)

C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [73]:
# get mean and std of evi from same year
df_evi2000 = getColstatisticBySearch(df=df, search_tag=r"evi_2000-\d\d", out_tag="evi_2000")
df_evi2001 = getColstatisticBySearch(df=df, search_tag=r"evi_2001-\d\d", out_tag="evi_2001")
df_evi2002 = getColstatisticBySearch(df=df, search_tag=r"evi_2002-\d\d", out_tag="evi_2002")
df_evi2003 = getColstatisticBySearch(df=df, search_tag=r"evi_2003-\d\d", out_tag="evi_2003")
df_evi2004 = getColstatisticBySearch(df=df, search_tag=r"evi_2004-\d\d", out_tag="evi_2004")
df_evi2005 = getColstatisticBySearch(df=df, search_tag=r"evi_2005-\d\d", out_tag="evi_2005")
df_evi2006 = getColstatisticBySearch(df=df, search_tag=r"evi_2006-\d\d", out_tag="evi_2006")
df_evi2007 = getColstatisticBySearch(df=df, search_tag=r"evi_2007-\d\d", out_tag="evi_2007")
df_evi2008 = getColstatisticBySearch(df=df, search_tag=r"evi_2008-\d\d", out_tag="evi_2008")
# get mean and std of ndvi from same year
df_ndvi2000 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2000-\d\d", out_tag="ndvi_2000")
df_ndvi2001 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2001-\d\d", out_tag="ndvi_2001")
df_ndvi2002 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2002-\d\d", out_tag="ndvi_2002")
df_ndvi2003 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2003-\d\d", out_tag="ndvi_2003")
df_ndvi2004 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2004-\d\d", out_tag="ndvi_2004")
df_ndvi2005 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2005-\d\d", out_tag="ndvi_2005")
df_ndvi2006 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2006-\d\d", out_tag="ndvi_2006")
df_ndvi2007 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2007-\d\d", out_tag="ndvi_2007")
df_ndvi2008 = getColstatisticBySearch(df=df, search_tag=r"ndvi_2008-\d\d", out_tag="ndvi_2008")

df out shape is (1080, 11)
(1080, 15)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 11)
(1080, 15)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)
df out shape is (1080, 12)
(1080, 16)

C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_std'] = std_devs/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_skew'] = skew_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_kurt'] = kurt_v/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out[f'{out_tag}_mean'] = means/10000
C:\Users\zhou.tang\AppData\Local\Temp\ipykernel_13404\2020424098.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [74]:
merge_list = [df_evi2000, df_evi2001, df_evi2002, df_evi2003, df_evi2004, df_evi2005, df_evi2006, df_evi2007, df_evi2008, 
            df_evi_jan, df_evi_feb, df_evi_mar, df_evi_apr, df_evi_may, df_evi_jun, df_evi_jul, df_evi_aug, df_evi_sep, df_evi_oct, df_evi_nov, df_evi_dec, 
            df_ndvi2000,df_ndvi2001,df_ndvi2002,df_ndvi2003,df_ndvi2004,df_ndvi2005, df_ndvi2006, df_ndvi2007, df_ndvi2008, 
            df_ndvi_jan, df_ndvi_feb, df_ndvi_mar, df_ndvi_apr, df_ndvi_may, df_ndvi_jun, df_ndvi_jul, df_ndvi_aug, df_ndvi_sep, df_ndvi_oct, df_ndvi_nov, df_ndvi_dec,
            ]
VIs_df = pd.concat(merge_list, axis=1)
VIs_df = pd.concat([df.iloc[:,:6],VIs_df], axis=1)
print(VIs_df)
VIs_df.to_csv("./NDVI_EVI_stat_2000-2008.csv", index=False)

      SiteID  Longitude_x  Latitude_x    Easting_x   Northing_x     CalVal_x  \
0        824   -80.673297   26.489618  731009.6175  280555.0742  calibration
1        818   -80.629703   26.664214  734816.5356  300047.1635  calibration
2        815   -80.516236   26.776278  745734.3602  312796.3002   validation
3        817   -80.474436   26.569130  750538.8963  289927.4316   validation
4        819   -80.691423   26.599105  728880.4467  292655.8679  calibration
...      ...          ...         ...          ...          ...          ...
1075     524   -81.445848   26.460529  654219.7001  275493.7896  calibration
1076     470   -81.447620   27.903338  650727.7593  435655.7481  calibration
1077    3012   -85.017295   30.217204  302181.6658  690394.2248  calibration
1078    3058   -81.668107   28.543391  627727.2782  506295.9652  calibration
1079     528   -81.891268   26.866231  609120.8594  319686.9694  calibration

      evi_2000_mean  evi_2000_std  evi_2000_skew  evi_2000_kurt  ...  \
0          0.378336      0.149050   4.014620e-07      -0.000167  ...
1          0.378209      0.075737  -2.266265e-05      -0.000126  ...
2          0.464436      0.175967  -3.591714e-05      -0.000086  ...
3          0.429736      0.185174  -7.196519e-05      -0.000097  ...
4          0.390318      0.188143  -6.296797e-05      -0.000064  ...
...             ...           ...            ...            ...  ...
1075       0.354173      0.059090   4.844955e-05      -0.000079  ...
1076       0.421900      0.073193  -1.913905e-05      -0.000092  ...
1077       0.392709      0.040905   2.284863e-05      -0.000146  ...
1078       0.270491      0.059824   6.043326e-05      -0.000157  ...
1079       0.244727      0.053993  -8.043499e-05       0.000004  ...

      ndvi_oct_skew  ndvi_oct_kurt  ndvi_nov_mean  ndvi_nov_std  \
0         -0.000094       0.000133       0.632911      0.044988
1         -0.000078      -0.000111       0.655022      0.038905
2         -0.000081      -0.000122       0.681844      0.081875
3          0.000031      -0.000009       0.638322      0.100806
4         -0.000036       0.000068       0.663844      0.057641
...             ...            ...            ...           ...
1075       0.000024      -0.000062       0.606722      0.027674
1076      -0.000080       0.000148       0.684167      0.030894
1077      -0.000179       0.000376       0.763178      0.024773
1078      -0.000015      -0.000115       0.437522      0.034510
1079       0.000032      -0.000141       0.631733      0.026314

      ndvi_nov_skew  ndvi_nov_kurt  ndvi_dec_mean  ndvi_dec_std  \
0          0.000061   1.063100e-07       0.566211      0.024785
1         -0.000146   2.928440e-04       0.610456      0.030922
2         -0.000108   1.664586e-05       0.621533      0.086533
3         -0.000124   8.620389e-05       0.576244      0.090548
4         -0.000115   1.390450e-04       0.633467      0.051172
...             ...            ...            ...           ...
1075       0.000027  -3.614091e-05       0.574733      0.028378
1076       0.000027  -1.327997e-04       0.687078      0.020277
1077      -0.000056  -1.409253e-04       0.755100      0.026562
1078      -0.000102   2.457550e-04       0.431956      0.042045
1079      -0.000038  -9.762928e-05       0.611078      0.028799

      ndvi_dec_skew  ndvi_dec_kurt
0         -0.000012      -0.000148
1         -0.000044      -0.000094
2          0.000003      -0.000182
3         -0.000005      -0.000055
4         -0.000042      -0.000082
...             ...            ...
1075      -0.000033      -0.000109
1076       0.000026      -0.000187
1077      -0.000080      -0.000006
1078      -0.000022       0.000043
1079      -0.000091       0.000280

[1080 rows x 174 columns]